export const userSelector = state => state.currentUser;
export const anyUserSelector = state => state.user;
export const followersSelector = state => state.followers;
export const followedSelector = state => state.followed;
export const userFollowedSelector = state => state.currentUserFollowed;
export const popularPostsSelector = state => state.popularPosts;
export const userPostsSelector = state => state.userPosts;
export const upvotedPostsSelector = state => state.votedPosts.up;
export const downvotedPostsSelector = state => state.votedPosts.down;
