export const USER_LOGOUT = 'USERLOGOUT';
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_FOLLOWERS = 'UPDATE_FOLLOWERS';
export const UPDATE_FOLLOWED = 'UPDATE_FOLLOWED';
